# Generated by Django 5.1.2 on 2024-11-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('attractions', models.TextField(blank=True)),
                ('visit_hours', models.TextField(blank=True)),
                ('best_time', models.TextField(blank=True)),
                ('duration', models.TextField(blank=True)),
                ('shopping', models.TextField(blank=True)),
                ('restaurants', models.TextField(blank=True)),
                ('hotels', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='destinations/images')),
                ('video', models.URLField(blank=True)),
            ],
        ),
    ]
