# Generated by Django 5.1.3 on 2024-11-16 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(help_text='Day of the trip (e.g., Day 1, Day 2)')),
                ('activities', models.TextField(blank=True, help_text='Activities for this destination on this day', null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.destination')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.itinerary')),
            ],
        ),
    ]
